### ISSUE TITLE
add power cone to conic models

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/MathProgBase.jl#101]
described my MOSEK http://docs.mosek.com/modeling-cookbook/cqo.html
and Vandenberghe http://www.seas.ucla.edu/~vandenbe/236C/lectures/conic.pdf

encourage more solvers to implement power cone!

**Comment by chriscoey** [comment]
OK to be fair, MOSEK just reformulates to do power cone with SOC, but this seems to require lots of extra variables and isn't super nice

**Comment by mlubin** [comment]
Duplicate of https://github.com/JuliaOpt/MathProgBase.jl/issues/70
