### ISSUE TITLE
Documentation - Solver Status Symbol

### ISSUE THREAD

**Issue by ccoffrin** [JuliaOpt/MathProgBase.jl#120]
These documentation pages do not clearly indicate what the semantics of the standard solver status symbols are for these classes of solvers,

https://github.com/JuliaOpt/MathProgBase.jl/blob/master/doc/lpqcqp.rst
https://github.com/JuliaOpt/MathProgBase.jl/blob/master/doc/conic.rst
https://github.com/JuliaOpt/MathProgBase.jl/blob/master/doc/nlp.rst

**Comment by mlubin** [comment]
The (limited) documentation for the status symbols is at http://mathprogbasejl.readthedocs.io/en/latest/solverinterface.html#status. It's uniform across all classes of solvers.

**Comment by mlubin** [comment]
Closing in favor of #164
