### ISSUE TITLE
get rid of default solver 

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/MathProgBase.jl#121]
`defaultMIPsolver` and `defaultConicsolver` break features in Pajarito because you can't call various functions on them (eg MathProgBase.supportedcones). Failing with defaults will make it confusing for users. Miles told me to submit an issue here to get rid of them because they were "implemented back when packages were slow to load, so the default solver avoided loading the packages until they were needed".

**Comment by mlubin** [comment]
This happened already
