### ISSUE TITLE
Deleting Constraints

### ISSUE THREAD

**Issue by odow** [JuliaOpt/MathProgBase.jl#125]
There has been some talk about disabling or deleting constraints from a model in memory (https://github.com/JuliaOpt/JuMP.jl/issues/606).

There is already support for deleting constraints at the solver level (i.e. in [Gurobi](https://github.com/JuliaOpt/Gurobi.jl/blob/master/src/grb_constrs.jl#L220)).

As a start perhaps there needs to be a MPB method `delconstr!(m, idx::Int)` where `idx` is the index of the constraint in the MathProgModel. 

This necessitates storing a mapping from MPB constraint index to solver index so that changing the RHS etc gets mapped as well.

This would be really handy for my work as well as https://github.com/JuliaOpt/StochDynamicProgramming.jl. We might have hundreds of LP's with thousands of constraints, of which maybe only 10% are needed. I want to be able to add a new constraint and delete 3 others without needing to rebuild the other 800 constraints while I'm at it. Currently I cache the deletions until the rebuild time is less than time gained from solving with fewer constraints.

@ccoffrin @henri-gerard @mlubin

**Comment by ccoffrin** [comment]
I am in favor of exposing the solver incremental constraint support.  It will be a necessary step to get the most out of a feature such as https://github.com/JuliaOpt/JuMP.jl/issues/606.

**Comment by mlubin** [comment]
@odow, have you done any benchmarking to see what's the potential gain from this? Internally the solver is going to need to do something equivalent to a rebuild anyway.

**Comment by mlubin** [comment]
People have been asking to remove constraints for quite a while but I've yet to see a single benchmark showing how useful it is.

**Comment by odow** [comment]
The solver is going to have to do a rebuild yes, but we don't have to rebuild the JuMP model. We typically build half the model then add constraints in an iterative fashion. I should possibly cache the half-built JuMP model rather than rebuilding it every time. Then there is less need for constraint deletion.

I agree that this needs to be benchmarked before anything gets implemented.

I've moved away from this work for a bit but I will be coming back to it in a month or two. Perhaps it's another item for @lkapelevich1 to add to her list of things to investigate if no one gets to it before then.

**Comment by lkapelevich1** [comment]
Sounds good @odow.

**Comment by joaquimg** [comment]
This could be closed right?

**Comment by mlubin** [comment]
Closed by https://github.com/JuliaOpt/MathProgBase.jl/pull/141
