### ISSUE TITLE
Model copy

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/MathProgBase.jl#140]
I know that Xpress exposes a method for copying the internal model.
Probably other solvers also have a similar method.

Incorporating it to MathProgBase would would enable its use in JuMP copy function, so that solving the copy does not requires rebuilding the model.

**Comment by mlubin** [comment]
Seems reasonable if it can be made to work

**Comment by joaquimg** [comment]
Just created the method and pushed into my fork, I also did it in Gurobi  joaquimg/Gurobi.jl@aecdeb95f958927e068735c89a4ab13b2a278f6a 

- delvars!  gets stuck in JuliaOpt/Gurobi.jl#60 fo the code:
```
m = MathProgBase.buildlp([-1,0],[2 1],'<',1.5,GurobiSolver())
sol = MathProgBase.solvelp(m)
MathProgBase.delvars!(m,[1])
sol = MathProgBase.solvelp(m)
```

- copy returns a warning that I do no know the solution exactely

```
julia> using Gurobi
INFO: Precompiling module MathProgBase.
WARNING: ignoring conflicting import of SolverInterface.copy into Gurobi
```

- delconstrs! and chgcoeffs! seem to work fine

**Comment by joaquimg** [comment]
@mlubin any idea why do I have this problem with ``copy``?

**Comment by mlubin** [comment]
There's no reason to define ``copy`` inside SolverInterface, just use ``Base.copy``.

**Comment by joaquimg** [comment]
Fair enough!

**Comment by mlubin** [comment]
Closed by https://github.com/JuliaOpt/MathProgBase.jl/pull/141
