### ISSUE TITLE
Using basis information to warmstart LP

### ISSUE THREAD

**Issue by jagomezr** [JuliaOpt/MathProgBase.jl#143]
Hi,

Is it possible to warmstart the LP solver with a primal or a dual feasible basis? 

Also, can basis information be extracted? I'm currently using:

MathProgBase.getbasis(model)

which returns something like this:
(Symbol[:Basic,:Basic,:NonbasicAtLower,:Basic,:NonbasicAtLower,:Basic],Symbol[:NonbasicAtLower,:NonbasicAtLower,:NonbasicAtLower,:NonbasicAtLower])

I can see the first vector is the column basis and the second one is the row basis. Is there a way of getting this information as a vector of zeros and ones?

Thanks

**Comment by mlubin** [comment]
> Is it possible to warmstart the LP solver with a primal or a dual feasible basis?

I don't believe that we have an interface to provide a starting basis.

Sorry your question wasn't answered in a timely manner. In the future it's best to ask usage questions like these at https://discourse.julialang.org/.
