### ISSUE TITLE
missing getdual() for LPQPtoConicBridge

### ISSUE THREAD

**Issue by ktarplee** [JuliaOpt/MathProgBase.jl#146]
When using an LP solver (`ClpSolver`) to construct a `ConicModel` a `LPQPtoConicBridge` is created.  The `AbstractConicModel` supports `getdual()` but the bridge does not.

The error is:
```
MethodError: no method matching getdual(::MathProgBase.SolverInterface.LPQPtoConicBridge)
```

**Comment by blegat** [comment]
@ktarplee This should be fixed on master, i.e. if you do
```
Pkg.checkout("MathProgBase")
```

**Comment by ktarplee** [comment]
This fixed my issue.   Thanks
