### ISSUE TITLE
Documentation in PDF?

### ISSUE THREAD

**Issue by cossio** [JuliaOpt/MathProgBase.jl#154]
There should be a link in https://mathprogbasejl.readthedocs.io to dowlnoad the documentation in PDF version. 

This is very convenient for offline access.

**Comment by mlubin** [comment]
If you're volunteering to figure it out, sure. You can also build the pdf locally by following the readme in the ``doc`` directory.

ReadTheDocs is pretty broken, and if there's any effort being put into documentation, it should probably be focused on moving towards Documenter.jl.

**Comment by cossio** [comment]
I have no idea how to fix this.

**Comment by mlubin** [comment]
We're in the same boat.

**Comment by mlubin** [comment]
Closing in favor of #169
