### ISSUE TITLE
Quadratic constraints in generalized conic form (#168)

### ISSUE THREAD

**Issue by blegat** [JuliaOpt/MathProgBase.jl#165]
It would be nice to allow quadratic constraints for Conic Model as well. It would allow for instance to solve BMIs (we still need a solver that supports it like [PENBMI](http://www.penopt.com/penbmi.html).
Related: https://github.com/MPF-Optimization-Laboratory/ConicIP.jl/issues/15

**Comment by mlubin** [comment]
closing in favor of https://github.com/JuliaOpt/MathProgBase.jl/issues/168
