### ISSUE TITLE
Solver Attributes

### ISSUE THREAD

**Issue by odow** [JuliaOpt/MathProgBase.jl#188]
Come up with a list of solver specific attributes. Supports
- [ ] returning duals
- [ ] changing coefficients
- [ ] adding constraints
- [ ] deleting constraints
- [ ] column generation
- [ ] for each solver independent parameter, do you support setting (i.e. timelimit, silent...)
- [ ] supports sets (same for model)
- [ ] modifying objective
- [ ] quadratic objective
- [ ] SOC through quadratic encoding (i.e. Gurobi)

**Comment by mlubin** [comment]
This basically lets us resolve https://github.com/JuliaOpt/JuMP.jl/issues/83 (2nd oldest open issue on JuMP)

**Comment by mlubin** [comment]
- can copy model

**Comment by mlubin** [comment]
As of https://github.com/JuliaOpt/MathProgBase.jl/pull/173/commits/0c92ff43e9801ff99b67df656a9fb2b66612b8c0 we have a concept of a solver attribute

**Comment by mlubin** [comment]
Re-open at MathOptInterface if appropriate
