### ISSUE TITLE
Free KNITRO in nlp tests

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/MathProgBase.jl#196]
It turns out that if one has KNITRO floating license it needs to be freed before solving a new model.
In order to use nlp test we need to use `MathProgBase.freemodel!(m)` in many places.

I would like to modify the test/nlp.jl to include that.

Should I check if the solver is KNITRO or do we guarantee it is a no-op everywhere else?

**Comment by mlubin** [comment]
You can check if `method_exists`.

**Comment by joaquimg** [comment]
I will open a PR then
