### ISSUE TITLE
Does the cbget method include the MIP cuts count? 

### ISSUE THREAD

**Issue by CBongiova** [JuliaOpt/MathProgBase.jl#226]
Hello, 

I would like to retrieve the information contained in the summary section at the end of the Gurobi log (http://www.gurobi.com/documentation/8.0/refman/mip_logging.html) 

I am particularly interested in knowing if there is a way to save the number of cutting planes applied (similarly to MIP_CUTCNT in http://www.gurobi.com/documentation/8.0/refman/callback_codes.html#sec:CallbackCodes). 

Do you support a way to retrieve such information in MathProgBase? 

Thanks!

**Comment by mlubin** [comment]
Closing this issue in favor of https://discourse.julialang.org/t/does-anyone-know-how-to-retrieve-the-number-of-generated-cuts-in-the-informational-callback/15370. Please cross-reference when posting the same question in multiple places.
