### ISSUE TITLE
Quick question: MathProgBase.setparameters!() does not accept keyword arguments?

### ISSUE THREAD

**Issue by jyg1124** [JuliaOpt/MathProgBase.jl#228]
I am using Julia 0.6.4 & MathProgBase 0.7.7.
MathProgBase.setparameters!(CplexSolver(),Silent=true) was working recently, but now it prints an error message. May I ask why?

![image](https://user-images.githubusercontent.com/19360543/47338300-48f08a80-d6d2-11e8-8038-00c850cdd82a.png)

**Comment by mlubin** [comment]
That's not intended. It's a bug in CPLEX.jl.
