### ISSUE TITLE
Create a model with CPLEX as a solver

### ISSUE THREAD

**Issue by ZacharieALES** [JuliaOpt/MathProgBase.jl#240]
Hello,

It is more a question than a bug sorry about that but I don't know where to get an answer...
I would like to create a simple model with CPLEX as a solver. What I hoped would work was:
`julia> model = MPB.linprog([-1,0],[2 1],'<',1.5, CPLEX.Optimizer)`
but it returns the error:
`ERROR: MethodError: no method matching linprog(::Array{Int64,1}, ::Array{Int64,2}, ::Char, ::Float64, ::CPLEX.Optimizer)`

Could you tell me how I can do that?

**Comment by ZacharieALES** [comment]
I did not realise that the package was not maintained anymore.

**Comment by mlubin** [comment]
Yes, please use JuMP instead.
