### ISSUE TITLE
addvar! method that specifies variable type

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/MathProgBase.jl#40]
E.g.  `addvar!(m, lb, ub, coeff, vtype::Char)`. This will be useful for SCIP where variables are created one-by-one and the variable type is asked for during construction.

**Comment by joaquimg** [comment]
Xpress also supports setting type while adding variables, should we work on this issue? I could help with Gurobi (and possibly with GLPK its possible).

**Comment by joehuchette** [comment]
Is this something you would find helpful?

**Comment by joaquimg** [comment]
It would just make loading the model marginally fast, not much significant. I was just offering to close the issue since I am working on the solver interfaces now.

**Comment by joehuchette** [comment]
I'm fine adding this to the interface. @mlubin?

**Comment by mlubin** [comment]
Same comment as in #142. Is this optional? What happens if a solver only supports this method and doesn't implement ``setvartype!``?

**Comment by joehuchette** [comment]
We could have a fallback like:
```jl
function addvar!(m, lb, ub, coeff, vtype::Symbol)
    typ = getvartype(m)
    addvar!(m, lb, ub, coeff)
    setvartype!(m, [typ, vtype])
end
```

**Comment by mlubin** [comment]
We can't have adding n variables be an O(n^2) operation

**Comment by mlubin** [comment]
We developed a SCIP interface without needing this change. I'll close this.
