### ISSUE TITLE
Quadratic-to-conic should ignore zero terms?

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/MathProgBase.jl#61]
The [assertion here](https://github.com/JuliaOpt/MathProgBase.jl/blob/9ddb6026b7817ba5e1f938b0eaea6448317dbfb9/src/SolverInterface/quad_to_conic.jl#L38) errors out if, e.g. the row and column index vectors are not identical, even if the off-diagonal terms have zero coefficients. This comes up in the vectorized stuff in JuMP, when we do something like ``x'Q*x``. Should we relax this?

**Comment by mlubin** [comment]
Could you expand on the use case? Why would you want to do ``x'Q*x`` when the only form accepted is ``x'x``?

**Comment by joehuchette** [comment]
Not much of a use-case, I essentially did ``x'*[1 0 0; 0 1 0; 0 0 -1]*x`` and it didn't work. It's a marginal use-case, but one that someone else is bound to run into at some point.

**Comment by joehuchette** [comment]
Also, considering this is a translation layer, it seems like it should be relatively robust to things like this.

**Comment by mlubin** [comment]
Given that this has a very special meaning, I think it's okay to be strict here. It's bound to be confusing one way or the other, e.g., why it works for 
```Q = [1 0 0; 0 1 0; 0 0 -1]``` 
but not 
```Q= [1 1e-13 0; 1e-13 1 0; 0 0 -1]```.

**Comment by mlubin** [comment]
This would also make the models harder to read since you wouldn't know when someone is adding a conic constraint.

**Comment by joehuchette** [comment]
On the other hand, it's not at all transparent why this works with e.g. Gurobi but fails with ECOS.

**Comment by mlubin** [comment]
Maybe JuMP should tidy up zeros before sending the problem to the solver?

**Comment by joehuchette** [comment]
Maybe, but again this seems like the job of the translation layer. You'd run into the same inconsistent behavior between Gurobi and ECOS using the MPB layer directly.

**Comment by mlubin** [comment]
Fair enough, could you open a PR with the fix?

**Comment by mlubin** [comment]
Closed by #62
