### ISSUE TITLE
Primal dual warmstarts

### ISSUE THREAD

**Issue by madeleineudell** [JuliaOpt/MathProgBase.jl#64]
I'd like to add the setwarmstart! functionality to SCS.jl. For the purposes of warmstarting SCS, it would be quite useful to have a primal & dual warmstart. But doing this requires a change to the MathProgBase interface, I think. For a minimally breaking change, I propose the following signature:

``` julia
setwarmstart!(m::MathProgModel, v; kwargs...)
```

which, in SCS.jl, would be implemented as

``` julia
function setwarmstart!(m::SCSMathProgModel, primal_sol; dual_sol=Float64[], kwargs...)
    m.primal_sol = primal_sol
    m.dual_sol = dual_sol
    m
end
```

while all other solvers would ignore all keyword arguments. (For now, at least.)

Are there any solutions that don't require modifying the signature of `setwarmstart!` in all solvers that have implemented it?

**Comment by mlubin** [comment]
We could just add a new method called ``setdualwarmstart!``. One can check if the solver supports the capability by checking if the method exists, so this wouldn't cause any breaking changes.

**Comment by IainNZ** [comment]
I like `setdualwarmstart!` because it kind of feels more MPB-ey.

**Comment by madeleineudell** [comment]
Warmstarts come from two places: user intuition, and previous problem
solutions. Users rarely have intuition for dual warmstarts. So for the
purposes of Convex.jl, I guess it might make more sense for us to just use
the previous MathProgModel and reload the problem data into it (which would
preserve the primal (and dual and slack and whatever) solutions already
stashed in the MathProgModel data structure), rather than calling
setwarmstart! explicitly.

Can you think of a scenario where we *do* need `setdualwarmstart!` ?

On Sun, Mar 22, 2015 at 11:24 AM, Iain Dunning <notifications@github.com>
wrote:

> I like setdualwarmstart! because it kind of feels more MPB-ey.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/MathProgBase.jl/issues/64#issuecomment-84670250>
> .
>



-- 
Madeleine Udell
PhD Candidate in Computational and Mathematical Engineering
Stanford University
www.stanford.edu/~udell

**Comment by mlubin** [comment]
Ipopt and other nonlinear support solvers setting initial lagrange multipliers. (This method will require a slightly different definition from the conic dual version.) I agree that it's not something most users will want to interact with, but I don't see the harm in exposing it at the MPB level anyway.

**Comment by tkelman** [comment]
Bump. My labmates need dual warmstarts. What needs doing here and in JuMP for that?

**Comment by mlubin** [comment]
This discussion was before the split between nonlinear and conic models, so Madeleine's concerns are likely orthogonal to yours. If you'd like a ``setdualwarmstart!`` for NLPs, propose a change to MPB, implement it in Ipopt.jl, and then bug us on the JuMP side.

**Comment by tkelman** [comment]
What does the change need to look like here? Just a new method?

**Comment by mlubin** [comment]
I'd say so.

**Comment by mlubin** [comment]
I'm intending for this to be addressed by #164

**Comment by chriscoey** [comment]
relevant - we got SCS warmstarts partially working for Pajarito. specifically, we used `setbvec!` to change the b vector and then started SCS from it's previous solution by giving it the `warm_start = true` option

see https://github.com/JuliaOpt/Pajarito.jl/issues/372 and https://github.com/JuliaOpt/SCS.jl/issues/77

**Comment by mlubin** [comment]
MathOptInterface supports primal and dual warm starts
