### ISSUE TITLE
update conicSDPtest

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/MathProgBase.jl#78]
The test hasn't been updated for the new symmetric definition of the SDP cone.

**Comment by tkelman** [comment]
While at it, should travis be turned on here?

**Comment by mlubin** [comment]
Sure, but what exactly should be tested at this level?

**Comment by tkelman** [comment]
Good question... tagged versions of the modeling languages (+a few solvers) against master of mathprogbase? That may or may not make any sense to do, I'm not sure.
