### ISSUE TITLE
In-place evaluations should be named `!`

### ISSUE THREAD

**Issue by dpo** [JuliaOpt/MathProgBase.jl#79]
The methods `eval_grad_f()`, `eval_jac_g()`, `eval_hesslag()` and `eval_hesslag_prod()` all fill in one of their input arguments. By convention, it might be better to rename them `eval_grad_f!()`, `eval_jac_g!()`, `eval_hesslag!()` and `eval_hesslag_prod!()`. Hopefully, this doesn't mean too much breakage...

**Comment by mlubin** [comment]
Oh, one reason why we don't have the ``!`` is that the argument modified isn't the first one. From what  I understand, the ``!`` convention usually means that the first argument is modified. So if we do rename, we should likely reorder the arguments as well.

**Comment by dpo** [comment]
Ah, didn't realize that. It would still be intuitive for those methods to be named `!` I feel.

**Comment by mlubin** [comment]
Doesn't seem like this will happen
