### ISSUE TITLE
mixintprog example throws a no method matching error

### ISSUE THREAD

**Issue by MichaeLeroy** [JuliaOpt/MathProgBase.jl#81]
I'm new to this package, so I tried to start with a simple case, the binary knapsack problem solution shown  in the [manual](https://mathprogbasejl.readthedocs.org/en/latest/mixintprog.html#mixed-integer-programming manual).  Unfortunately on my installation, this example throws a "no method matching" error:

    julia> using MathProgBase

    julia> using Cbc

    julia> mixintprog(-[5.,3.,2.,7.,4.],[2. 8. 4. 2. 5.],'<',10,'I',0,1)
    ERROR: `mixintprog` has no method matching mixintprog(::Array{Float64,1}, ::Array{Float64,2}, ::Char, ::Int64, ::Char, ::Int64, ::Int64)

    julia> versioninfo()
    Julia Version 0.3.7
    Commit cb9bcae* (2015-03-23 21:36 UTC)
    Platform Info:
      System: Linux (x86_64-linux-gnu)
      CPU: Intel(R) Core(TM) i7-3610QM CPU @ 2.30GHz
      WORD_SIZE: 64
      BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Sandybridge)
      LAPACK: libopenblas
      LIBM: libopenlibm
      LLVM: libLLVM-3.3

    julia> Pkg.installed("MathProgBase")
    v"0.3.14"

    julia> Pkg.installed("Cbc")
    v"0.1.7"

I'll study the source to gain some insight and will update this issue with a suggestion for an example that works when I succeed in running <code>mixintprog</code>.  Meanwhile please feel free to let me know if I'm making some silly newbie error in this attempt.

**Comment by mlubin** [comment]
Thanks for reporting this, the example was broken. The correct syntax is:
```
mixintprog(-[5.,3.,2.,7.,4.],[2. 8. 4. 2. 5.],'<',10,:Int,0,1)
```
