### ISSUE TITLE
A getvarduals() for the conic interface

### ISSUE THREAD

**Issue by ulfworsoe** [JuliaOpt/MathProgBase.jl#84]
The method `getreducedcosts()` returns dual variable information, but according to @mlubin is not part of the conic interface. I propose a `getconicvarduals()` (for lack of a better name), that returns the dual solution values. This can in principle be computed as
```
s = A'y+c
```
but as solvers work in epsilon-precision, the solver's dual variable may only be approximately equal to `A'y+c`. In some cases this may make a difference when validating eps-optimality/-feasibility.

**Comment by mlubin** [comment]
This seems like a reasonable addition.
CC @madeleineudell @bodono

**Comment by chriscoey** [comment]
@mlubin @emreyamangil could this be helpful for us on Pajarito potentially?

**Comment by mlubin** [comment]
Yep

**Comment by emreyamangil** [comment]
Yupp, basically our dual cut at the moment
