### ISSUE TITLE
Passing extra variables to the eval_f and other functions.

### ISSUE THREAD

**Issue by GravityAssisted** [JuliaOpt/MathProgBase.jl#92]
Is there a way to pass user defined immutable type arrays to the functions (as additional function arguments or vector ) ? I need those to evaluate my cost function and gradients. I am trying to use the IPOPT.jl package.

thanks,
Nitin

**Comment by mlubin** [comment]
You can use the NLP evaluator object to store any data you need to evaluate the callbacks.

**Comment by GravityAssisted** [comment]
Thanks for your reply. Apologize for the late response. I was on month long vacation.
Is there some documentation which briefly describes, on how to define the AbstractNLPEvaluator ? I was looking through the documentation website but the NLP pages don't contain much information on how to define and use the AbstractNLPEvaluator.

**Comment by GravityAssisted** [comment]
I asked the question too soon. Going through the example, I think its just a regular composite type. I am still learning Julia :)

**Comment by mlubin** [comment]
Closing this issue, if you have further questions feel free to ask on the julia-opt list.

**Comment by GravityAssisted** [comment]
Sure, thanks.
