### ISSUE TITLE
``getrawsolver`` doesn't work for bridges

### ISSUE THREAD

**Issue by joehuchette** [JuliaOpt/MathProgBase.jl#96]
```jl
using JuMP, MathProgBase, Gurobi
m = Model(solver=GurobiSolver())
@defVar(m, x)
@addConstraint(m, norm(x) <= 1)
buildInternalModel(m)
MathProgBase.getrawsolver(getInternalModel(m))
```
```
ERROR: MethodError: `getrawsolver` has no method matching getrawsolver(::MathProgBase.SolverInterface.LPQPtoConicBridge)
```
You can work around it by accessing the fields directly (``MathProgBase.getrawsolver(getInternalModel(m).lpqpmodel)``), but I think the abstraction should probably do that for you. CC @mlubin

**Comment by mlubin** [comment]
Yeah, just add the missing method

**Comment by joehuchette** [comment]
What about all the other functions you might want to call on a bridge that aren't currently defined?

**Comment by mlubin** [comment]
Lazy features?
